# Generated by Django 5.0.3 on 2024-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly', '0003_rename_chaper_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(unique=True),
        ),
    ]
