# Generated by Django 5.0.3 on 2024-05-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly', '0011_alter_bookmark_user_follow_follow_unique_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
