# Generated by Django 5.0.3 on 2024-04-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='filepath',
        ),
        migrations.CreateModel(
            name='Chaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('chapter_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lastupdated', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bookly.book')),
            ],
        ),
    ]
