# Generated by Django 5.0.3 on 2024-04-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookly', '0002_remove_book_filepath_chaper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chaper',
            new_name='Chapter',
        ),
    ]
