# Generated by Django 5.0.3 on 2024-04-26 07:50

import bookly.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookly', '0006_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to=bookly.models.get_cover_upload_to),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('book', 'chapter_number'), name='unique_chapter_number'),
        ),
    ]
